language: php
sudo: required
dist: trusty
services:
  - docker

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=5.4
    - php: 5.6
      env: WP_VERSION=5.3
    - php: 5.6
      env: WP_VERSION=5.2
    - php: 5.6
      env: WP_VERSION=5.1
    - php: 5.6
      env: WP_VERSION=5.0
    - php: 5.6
      env: WP_VERSION=4.9
    - php: 5.6
      env: WP_VERSION=4.8
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.6
      env: WP_VERSION=4.6
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.6
      env: WP_VERSION=4.3
    - php: 5.6
      env: WP_VERSION=4.2
    - php: 5.6
      env: WP_VERSION=4.1
    - php: 5.6
      env: WP_VERSION=4.0
    - php: 5.6
      env: WP_VERSION=3.9
    - php: 5.6
      env: WP_VERSION=3.8
    - php: 7.1
      env: WP_VERSION=4.6 SWITCH_TO_PHP=5.2
    - php: 7.1
      env: WP_VERSION=4.7 SWITCH_TO_PHP=5.2
  fast_finish: true
  allow_failures:
    - env: WP_VERSION=3.8
      php: nightly
    - env: WP_VERSION=3.8
      php: 7.1
    - env: WP_VERSION=latest
      php: nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.phpbrew

script: ./tests/bin/run-wp-unit-tests.sh
after_script: ./tests/bin/after-run-wp-unit-tests.sh

branches:
  only:
  - master
  - develop

notifications:
  slack:
    rooms:
      - secure: g3L0XaiaUjUeBoNMLXx4pdz+7JudZhFGPY1mOX1WkC4B0zo+M/tGdhLLz/
    on_success: never
    on_failure: change
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/00b1df026574cdaeb815
    on_success: never  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
  email:
    on_success: never # default: change
    on_failure: change # default: always
